### ISSUE TITLE
我想咨询一下

### ISSUE THREAD

**Issue by chengxuyuanluyu** [getActivity/AndroidProject-Kotlin#11]
gradle导入apply plugin: 'kotlin-android-extensions'
可以直接引用xml的id
现在还可以用嘛，我看到项目里并没有用

**Comment by luckerbai** [comment]
这个被弃用了吧，现在推荐使用ViewBinding。

**Comment by getActivity** [comment]
小伙子，你问我这个问题的时候有没有反向思考过？我为什么要用这个东西？
