### ISSUE TITLE
图片挂了

### ISSUE THREAD

**Issue by lujun525** [getActivity/AndroidProject-Kotlin#12]
文档里图片都挂了

**Comment by getActivity** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28616817/159155803-84a0e03c-1878-4781-abe0-19e4ed8d2067.png">

**Comment by getActivity** [comment]
小伙子，我又去检查了一下，图片显示是完全 ok 的，你不能显示应该是被 Github 墙了，建议开启 VPN 后再试一下。
