### ISSUE TITLE
轮子哥，感谢您的辛苦付出

### ISSUE THREAD

**Issue by zkzk7749** [getActivity/AndroidProject-Kotlin#13]
轮子哥，感谢您的辛苦付出，请问能不能把你的dialog系列封装一下啊，特比喜欢你的东西

**Comment by getActivity** [comment]
https://github.com/getActivity/AndroidProject-Kotlin/blob/master/HelpDoc.md

**Comment by getActivity** [comment]
小伙子，文档上面已经写的不要再问了，你就算知道，再提及这个问题也不会有任何效果，除非你能说服我，但是过程非常艰难，你要拿出充分的理由说服我去做这件事，这样做比现在好在哪里？做完后会出现什么问题？相比较后是不是利大于弊？
