### ISSUE TITLE
轮子哥，webview池化一下吧

### ISSUE THREAD

**Issue by RDSunhy** [getActivity/AndroidProject-Kotlin#15]
想知道您会怎么对webview池化。包括对webview的白屏检测等等。

**Comment by getActivity** [comment]
池化是什么？

**Comment by getActivity** [comment]
还有 AndroidProject 为什么要做白屏检测？现在的背景是什么？如果要做的话市面上有什么解决方案？做完对大多数人的帮助又是什么？

**Comment by RDSunhy** [comment]
> 池化是什么？

一个webview容器化管理类吧。 webview的初始化比较耗时，在app启动时就预先初始化好 n 个webview（n 根据手机内存大小计算），当需要打开webactivity时，activity中的webview从容器中取出然后addView到当前页面，页面销毁时再放回容器复用。

**Comment by RDSunhy** [comment]
> 

白屏检测，应该很多app都有尤其是有自己的H5页面的项目。背景就是当webview loadUrl 成功，但是页面空白的情况，算是一种异常检测吧。

**Comment by getActivity** [comment]
@RDSunhy 不会考虑做，原因很简单，并不是大多数人都会用到这两个功能，AndroidProject 不是为某个人定制，而不是为我定制，做任何功能都会第一考虑大多数人的需求，因为如果把 AndroidProject 每一个功能都补齐，又或者把已做完的功能无止境地叠加需求，那么代码就会变得很臃肿，包体也会随着暴增，但实际情况是大多数人并没有这种需求，所以我在考虑是否加这个功能的时候，会优先看大多数人有没有这样的需求，如果有才会考虑，如果没有的话是一定不会考虑的。正如我之前在文档中说的，我的定位做是一个代码架构设计，而不是一个代码的杂货铺。
