### ISSUE TITLE
返回值用Response接收时  到ui层的listener回调是异步的 response在finally代码块中已经被关闭了 导致取不到响应体 

### ISSUE THREAD

**Issue by z102339** [getActivity/AndroidProject-Kotlin#16]

**Comment by getActivity** [comment]
[EasyHttp-11.2.aar.zip](https://github.com/getActivity/AndroidProject-Kotlin/files/8918985/EasyHttp-11.2.aar.zip)

**Comment by getActivity** [comment]
收到，问题已经修复，多谢小伙子的提醒。
