### ISSUE TITLE
轮子哥，请问Crash处理类能提取出成一个库吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [getActivity/AndroidProject-Kotlin#18]

**Comment by getActivity** [comment]
https://github.com/getActivity/AndroidProject-Kotlin/blob/master/HelpDoc

**Comment by getActivity** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/28616817/181011969-9a93f206-384a-4ef0-b870-f1c88410672b.png">

**Comment by getActivity** [comment]
小伙子，暂时不考虑这样做。

**Comment by SaltedFish-Extreme** [comment]
> 小伙子，暂时不考虑这样做。

好的，麻烦轮子哥了👌
