### ISSUE TITLE
轮子哥AndroidProject-Kotlin版本啥时候出来啊

### ISSUE THREAD

**Issue by JIanyag** [getActivity/AndroidProject-Kotlin#2]
轮子哥AndroidProject-Kotlin版本啥时候出来啊

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/114554551-6d24f500-9c99-11eb-83c3-54f52d0f5ad1.png)

**Comment by getActivity** [comment]
小伙子，从目前的结果来看，AndroidProject Kotlin 版本的优先级不会很高，所以可能要推迟到今年的 10 月份之后。

**Comment by luckerbai** [comment]
还是挺期待的

**Comment by liverloop** [comment]
Koltin版本优先级希望能提高下，已经全部转kotlin开发了

**Comment by is1988** [comment]
谢谢作者，很期待哟

**Comment by luckerbai** [comment]
哇，明天就国庆了，10月份之后Kotlin版本是不是就快了呢？

**Comment by chenjim** [comment]
建议跟Java版本放一个仓库，不同分支

**Comment by liverloop** [comment]
轮子哥，kt版本啥时候能出来？

**Comment by getActivity** [comment]
@chenjim 光是转一个 Java 类到 Kotlin 有几百个报错和几百个警告，AndroidProject 目前有上千个类，你去试试就知道什么叫分分钟痛苦了。

**Comment by liverloop** [comment]
> 选择Java版本目录，AS中右键“Convert Java File To Kotlin File”，分分钟出来，哈哈 @liverloop

目前Java kt混合开放也能用

**Comment by ehuiz** [comment]
轮子哥，kt版本啥时候能出来？

**Comment by getActivity** [comment]
小伙子，AndroidProject Kotlin 版本的代码已经提交，拉取一下代码即可。
