### ISSUE TITLE
android10以上系统图片裁剪后上传头像失败

### ISSUE THREAD

**Issue by ZhungJeffrey** [getActivity/AndroidProject-Kotlin#20]
## 问题描述

* 框架版本【必填】：V13.2

* 问题描述【必填】：小米手机mix4，系统android11，个人主页上传头像裁剪后上传文件失败，

* 复现步骤【必填】：点击上传头像，图片裁剪，上传失败，提示图片扩展名不被接受，debug发现header中的filename不是图片的filename，不带图片格式，所以服务器不接受。不清楚这个filename是怎么赋值的。issue上传了调试截图，大佬一看应该就明白

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：小米手机mix4

* 出现问题的安卓版本【必填】：android11

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分，mix4  Android11系统会出现，mix2  android9系统不出现，推断和存储分区有关

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是
* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：不确定，因为这个是向服务器上传才出现的问题，AndroidProject 不能的上传图片

* 使用原生的权限 API 是否会出现该问题【必答】：否（排查一下是不是 AndroidProject 的代码存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）
*
![F4343D6B-486D-4e6f-A600-2F8E251CF7AE](https://user-images.githubusercontent.com/21453207/186130719-3193840f-e763-4149-988e-9b713cd1680b.png)
![A28999BC-8BE4-4654-A5B0-FAB27B9989A2](https://user-images.githubusercontent.com/21453207/186130755-d3171261-3f76-4d56-b8e3-a4d4b64b3587.png)

**Comment by getActivity** [comment]
小伙子，你这个问题不是 EasyHttp 的问题？不是应该得提给 EasyHttp ？

**Comment by getActivity** [comment]
还有这个请求头不是 EasyHttp 添加的，你自己排查一下看看是从哪里被添加的？
<img width="538" alt="image" src="https://user-images.githubusercontent.com/28616817/186431975-2947a2c4-c7bb-42e4-8b60-dbba93a73c5b.png">

**Comment by getActivity** [comment]
如果确定是框架的问题再来找我

**Comment by getActivity** [comment]
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/28616817/186900524-26865aa0-9e14-4eac-87ee-dd5bd8bd7802.png">
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/28616817/186900572-50fad1c5-4e60-42a3-bd66-52cf42bb9650.png">
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/28616817/186900754-0f2ae816-1dd9-4a84-a5c3-bb51ba72a288.png">

**Comment by getActivity** [comment]
@ZhungJeffrey 小伙子，我按照你说的步骤进行操作，并没有复现到该问题。

**Comment by getActivity** [comment]
问题后续已经私下解决，原因是使用框架旧版本导致的。
