### ISSUE TITLE
导入报错，目前找不到解决办法

### ISSUE THREAD

**Issue by ylmyg** [getActivity/AndroidProject-Kotlin#21]
## 问题描述

* 框架版本【必填】：v13.2

* 问题描述【必填】：导入studio报错
Build file 'D:\YG2\GITDEMO4\AndroidProject-Kotlin-master\app\build.gradle' line: 3
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'kotlin-kapt'.
   > Extension with name 'kotlin' does not exist. Currently registered extension names: [ext, base, defaultArtifacts, sourceSets, reporting, java, javaToolchains, buildOutputs, android, androidComponents, aspectjx, kapt]

* 复现步骤【必填】：每次导入都报错

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：Redmi

* 出现问题的安卓版本【必填】：android10

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分 目前只有一台手机

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是

**Comment by getActivity** [comment]
@ylmyg 小伙子，你换一台电脑试一下有没有这个问题，如果没有另外一台电脑的话，可以找身边的朋友或者同事帮你跑这个项目看看。

**Comment by ylmyg** [comment]
请问下我把项目中gradle版本改成了我本地的版本 7.1.1 kotlin 版本改成1.6.21 是否是导致错误的原因？

**Comment by getActivity** [comment]
小伙子，肯定有问题啊，不改代码运行有问题可能是我的代码有问题，但是你改了代码导致的问题就肯定不是我的问题，你如果想升级 Gradle 版本，那么就要做好兼容的准备，如果你不想做兼容，那么就不要试图去升级他。

**Comment by ylmyg** [comment]
好的，我直接用你的版本。为何你那么强？

**Comment by AreYReady** [comment]
刚刚直接运行起来。。。 @getActivity 想请教下，感觉项目里用到的jetpack库几乎没有，你怎么看这几个jetpack库的

**Comment by getActivity** [comment]
> 好的，我直接用你的版本。为何你那么强？

<img width="872" alt="image" src="https://user-images.githubusercontent.com/28616817/192126135-43dd858a-9de8-46ae-a1b6-ab9c68c7830e.png">

**Comment by getActivity** [comment]
> 刚刚直接运行起来。。。 @getActivity 想请教下，感觉项目里用到的jetpack库几乎没有，你怎么看这几个jetpack库的

@AreYReady 小伙子，这个问题文档上有写，你自己找文档看一下。
