### ISSUE TITLE
直接引入base和weight库后dimen识别不了

### ISSUE THREAD

**Issue by clbDream** [getActivity/AndroidProject-Kotlin#23]
## 直接引入base和weight库后dimen识别不了

* 框架版本【必填】：直接下载的最新版本的

* 问题描述【必填】：直接引入base和weight库后dimen识别不了

* 复现步骤【必填】：新建项目直接引入base和weight库后dimen识别不了

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：红米note9

* 出现问题的安卓版本【必填】：12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的权限 API 是否会出现该问题【必答】：否（排查一下是不是 AndroidProject 的代码存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

![image](https://user-images.githubusercontent.com/28987014/196651642-7db84038-b9e2-40f6-a11d-c884806bebd1.png)
![image](https://user-images.githubusercontent.com/28987014/196651768-039cd649-840c-4717-8d45-fd101a1c7470.png)
![image](https://user-images.githubusercontent.com/28987014/196651820-b358fcd5-e15a-46d1-9a58-56a71e879a1d.png)

**Comment by getActivity** [comment]
https://github.com/getActivity/AndroidProject/issues/102

**Comment by getActivity** [comment]
小伙子，这个不属于框架的问题，而是属于你的个人问题，需要你这边自行处理一下，我目前只处理框架的 Bug 和建议。

**Comment by clbDream** [comment]
知道原因了,新项目里面会默认开启这个属性,关闭即可
![image](https://user-images.githubusercontent.com/28987014/196891894-ff0ba8ce-24f8-4941-8faf-d50242502eca.png)

**Comment by devzwy** [comment]
> 小伙子，这个不属于框架的问题，而是属于你的个人问题，需要你这边自行处理一下，我目前只处理框架的 Bug 和建议。

小伙子，你吃了两碗粉却只付了一碗粉的钱
