### ISSUE TITLE
编译release版时报错

### ISSUE THREAD

**Issue by guodonghuang** [getActivity/AndroidProject-Kotlin#27]
## 问题描述

* 框架版本【必填】：V13.2

* 问题描述【必填】：编译release版时报错，C:/Users/me/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm/1.6.0/f3b8fd26c2e76d2f18cbc36aacb6e349fcb9fd5f/kotlinx-coroutines-core-jvm-1.6.0.jar!/META-INF/kotlinx-coroutines-core.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

* 复现步骤【必填】：编译release，或者打包release

* 是否必现【必填】：是

* 出现问题的手机信息【必填】： 

* 出现问题的安卓版本【必填】： Android 12

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，具体原因如下：

* 没有严格按照 issue 模板填写

请重新提一个 issue 并纠正以上问题
