### ISSUE TITLE
编译release的时候报错

### ISSUE THREAD

**Issue by guodonghuang** [getActivity/AndroidProject-Kotlin#28]
## 问题描述

* 框架版本【必填】：V13.1

* 问题描述【必填】：编译release的时候,或者打包release的时候报错：D:/MyDevelopmentSoft/android-studio/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.0/a40b8b22529b733892edf4b73468ce598bb17f04/kotlin-stdlib-1.6.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

* 复现步骤【必填】：编译release的时候,或者打包release的时候，打出来的release包无法正常安装使用

* 是否必现【必填】：是，升级了最新kotlin1.7.2也不行，应该是某处依赖了低版本kotlin，目前小菜无法解决，请大佬给以解决方案！！谢谢！！

* 出现问题的手机信息【必填】：所有

* 出现问题的安卓版本【必填】：所有

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频![16672857609695](https://user-images.githubusercontent.com/23655609/199176750-f29914d3-94f8-4692-ae84-1210c84276d0.png)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28616817/199236373-f8b6d7b6-da0a-4329-9a62-c76bc58bac89.png">

**Comment by getActivity** [comment]
小伙子，我测试了，并没有出现你说的那个问题，你确定用原汁原味的 AndroidProject-Kotlin 的工程打 release 包也能出现这个问题？

**Comment by guodonghuang** [comment]
以下配置下报错
classpath 'com.android.tools.build:gradle:4.1.2'

distributionUrl = https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip

**Comment by getActivity** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28616817/199496250-29e096db-0a1d-401b-bdb2-4211564ed2e1.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28616817/199496175-1d3cd98f-8ad5-416f-9aec-7d7e48bc3440.png">

**Comment by getActivity** [comment]
小伙子，我试过了，没有问题。

**Comment by guodonghuang** [comment]
好的，大佬，我修改了配置，现在问题也没了
