### ISSUE TITLE
kotlin早点更新哈  轮子哥

### ISSUE THREAD

**Issue by CPC-Coder** [getActivity/AndroidProject-Kotlin#3]

**Comment by CPC-Coder** [comment]
都12月了

**Comment by getActivity** [comment]
小伙子，在做了，工作比较忙，进度相对较慢，但是最近有可能会内测，可能还要一两个月才会正式发布。

**Comment by CPC-Coder** [comment]
给你点赞

**Comment by CPC-Coder** [comment]
轮子哥  提下建议
1.那aspectjrt 也可以备注下 一些资料和文档  自己没找到比较通俗的资料  相对晦涩
2. 可以加入rxjava相关的东西 demoActivity mvvm 现在比较多公司这方面
3.  jetpack相关
主要先出项目吧  这些可以后面迭代

**Comment by getActivity** [comment]
收到，多谢小伙子的建议

**Comment by CPC-Coder** [comment]
谢谢 轮子哥 看你的代码  学到了很多东西
感觉java的项目 dialog 可以 独立出 库 会好点

**Comment by getActivity** [comment]
小伙子，AndroidProject Kotlin 版本的代码已经提交，拉取一下代码即可。
