### ISSUE TITLE
请问如何进行手机平板及折叠屏尺寸动态适配的修改

### ISSUE THREAD

**Issue by guodonghuang** [getActivity/AndroidProject-Kotlin#31]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】没有

* 你觉得框架有什么不足之处？【必答】缺少手机平板尺寸适配的动态修改

* 你觉得该怎么去完善会比较好？【非必答】

1，怎么修改demo中的基础尺寸设置
2，怎么适配折叠屏，折叠和展示，其尺寸比例差别较大，展开后屏幕尺寸接近1:1,如何进行动态修改；

**Comment by getActivity** [comment]
小伙子，我来回答你的两个问题

1. 怎么修改demo中的基础尺寸设置：如果你有这个需要，请不要用 AndroidProject 默认携带的最小宽度通配符适配方案，而是考虑换成 AutoSize 这种动态适配方案，有一点需要的是，AutoSize 已经停更，后续使用遇到任何问题需要你自行解决。

2. 怎么适配折叠屏，折叠和展示，其尺寸比例差别较大，展开后屏幕尺寸接近1:1，如何进行动态修改：我没有折叠屏手机，不知道具体的效果，无法回答你这个问题

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
