### ISSUE TITLE
更新计划，我记得之前看过，现在找不到了

### ISSUE THREAD

**Issue by luckerbai** [getActivity/AndroidProject-Kotlin#35]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】有过类似问题，但是貌似未按照issue模板填写被关闭了。

* 你觉得框架有什么不足之处？【必答】没有。目前只有Bug、建议可选，选建议感觉靠谱点，毕竟只是想问问版本更新的计划？

* 你觉得该怎么去完善会比较好？【非必答】看了关于为什么不适用ViewBinding的说明，但是感觉还是使用ViewBinding更方便一些。当然，这只是自己的感受。有没有考虑使用Jetpack Compose的打算? 打扰了，谢谢。

**Comment by LeqiaoW** [comment]
感谢您的来信，邮件我已收到！

**Comment by getActivity** [comment]
小伙子，你这个问题我已经在文档上面写了，你回去仔细翻一下文档看看。

**Comment by getActivity** [comment]
小伙子，AndroidProject 目前暂无更新计划。

**Comment by luckerbai** [comment]
好的，了解，谢谢！
