### ISSUE TITLE
为什么构建成功后，运行项目，提示配置ndk

### ISSUE THREAD

**Issue by AdminQQZ** [getActivity/AndroidProject-Kotlin#36]
## 建议收集
![image](https://github.com/getActivity/AndroidProject-Kotlin/assets/12959954/492ce463-6a5d-44ec-bd5f-c79397a9e770)
这是截图

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？【必答】（你可以描述框架有什么令你不满意的地方）

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
目前 AndroidProject 不需要配置 NDK，我看 `local.properties` 没有配置 NDK 路径也可以正常运行，目前其他人也没有反馈过这个问题，如果你的电脑提示需要加上，那你加上就可以了。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
