### ISSUE TITLE
OnScrimsListener 监听回调方法中控件参数明明传的是 this ，为什么是可空类型？

### ISSUE THREAD

**Issue by anjiemo** [getActivity/AndroidProject-Kotlin#37]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】否

* 你觉得框架有什么不足之处？【必答】比较疑惑 OnScrimsListener 监听的回调方法 onScrimsStateChange 中，控件参数明明传的是 this ，为什么是可空类型？

* 你觉得该怎么去完善会比较好？【非必答】当前对象应该是不为空的吧，为什么要设计为可空的参数呢？直接非空不可以吗？

**Comment by getActivity** [comment]
如果不调用 setOnScrimsListener 方法，OnScrimsListener 是不是会为空？还有我之前设置了监听，现在如果要移除监听呢？

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
