### ISSUE TITLE
建议升级gradle7，这版本对构建速度有优化

### ISSUE THREAD

**Issue by AdminQQZ** [getActivity/AndroidProject-Kotlin#39]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）
* 否

* 你觉得框架有什么不足之处？【必答】（你可以描述框架有什么令你不满意的地方）
* 建议升级gradle7，这版本对构建速度有优化

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）
* 升级下

**Comment by LeqiaoW** [comment]
感谢您的来信，邮件我已收到！

**Comment by getActivity** [comment]
https://github.com/getActivity/AndroidProject/issues/103
