### ISSUE TITLE
当我把compileSdkVersion和compileSdkVersion改为34的时候出现一个问题！

### ISSUE THREAD

**Issue by GuoLiangjun123** [getActivity/AndroidProject-Kotlin#41]
## 问题描述

* 框架版本【必填】：没有版本

* 问题描述【必填】：当我把compileSdkVersion和compileSdkVersion改为34，run的时候提示Installation did not succeed. The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED，我已经在清单文件里面将SplashActivity的标签下加了android:exported="true"

* 复现步骤【必填】：先把compileSdkVersion和compileSdkVersion改为34，再在清单文件里面将SplashActivity的标签下加了android:exported="true"，然后打包app

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：小米10

* 出现问题的安卓版本【必填】：安卓13

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by LeqiaoW** [comment]
感谢您的来信，邮件我已收到！

**Comment by GuoLiangjun123** [comment]
<activity android:name="com.tencent.tauth.AuthActivity"
            android:exported="true"/>

> > 感谢您的来信，邮件我已收到！
> 
> 已解决，QQ登录的第三方库，自己在清单文件里面添加标签就行
