### ISSUE TITLE
当我新建一个空activity的时候会自动在app.gradle里添加依赖,并且运行失败

### ISSUE THREAD

**Issue by GuoLiangjun123** [getActivity/AndroidProject-Kotlin#42]
## 问题描述

* 框架版本【必填】：13.2

* 问题描述【必填】：右键选择new-activity-empty views activity新建了一个activity过后
* 1.会在app.gradle中新添加依赖
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

2.并且会在app.gradle文件顶部导入插件apply plugin: 'org.jetbrains.kotlin.android'
3.清单文件也被篡改与string文件也被篡改。
4.再打包运行的时候就会报错：Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

* 复现步骤【必填】：同问题描述

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：小米10

* 出现问题的安卓版本【必填】：13

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否
* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）
![1701325723735](https://github.com/getActivity/AndroidProject-Kotlin/assets/34742384/7dfd4ed7-3e67-46c7-ae70-232dd1fb7f27)
![1701325772468](https://github.com/getActivity/AndroidProject-Kotlin/assets/34742384/e4f2de90-d323-4bbe-ae38-a011ceb3da34)
![1701325811154](https://github.com/getActivity/AndroidProject-Kotlin/assets/34742384/ca47ad75-41ac-421e-8239-9b6055d2f902)
![1701325867484](https://github.com/getActivity/AndroidProject-Kotlin/assets/34742384/cef5b4d4-f650-4427-8bd4-8a575eaa1c5e)
![1701325932096](https://github.com/getActivity/AndroidProject-Kotlin/assets/34742384/b83df597-eb1f-48bc-978f-1e4b2476301f)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，你说的这个问题是 Android Studio 的问题吧？跟 AndroidProject 有啥关系呢？

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
