### ISSUE TITLE
希望增加recycleview样式支持

### ISSUE THREAD

**Issue by GuoLiangjun123** [getActivity/AndroidProject-Kotlin#43]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】没有

* 你觉得框架有什么不足之处？【必答】关于recyclerview可以增加多布局的封装

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
小伙子，这个问题文档上面不是已经写了？

**Comment by GuoLiangjun123** [comment]
> 小伙子，这个问题文档上面不是已经写了？

原生的 RecyclerView.Adapter 本身就支持多 type，只需要重写适配器的 getItemType 方法即可，具体用法不做过多介绍。
这个吗

**Comment by getActivity** [comment]
是的
