### ISSUE TITLE
proguard 配置引入 proguard-base.pro 打出来的包会比 getDefaultProguardFile('proguard-android-optimize.txt') 大 1M+

### ISSUE THREAD

**Issue by syxc** [getActivity/AndroidProject-Kotlin#44]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】
  没有

* 你觉得框架有什么不足之处？【必答】
  
  现在有两份 proguard 配置：
  ```
  配置 1
  proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-sdk.pro', 'proguard-app.pro'
  
  配置 2
  proguardFiles 'proguard-base.pro', 'proguard-sdk.pro', 'proguard-app.pro'
  ```
  其中 proguard-base.pro 是 base 模块 consumerProguardFiles 'proguard-base.pro' 方式引入的，配置 2 这么写只是方便对比。
  无意间发现，配置 2 打出来的包相比配置 1 打的包，会多出近 2M 左右大小。

* 你觉得该怎么去完善会比较好？【非必答】
  阿轮，空了的话，可否优化一下 proguard 的配置，在不影响正常功能的前提下，控制一下打出包的大小。

**Comment by getActivity** [comment]
<img width="1228" alt="image" src="https://github.com/getActivity/AndroidProject-Kotlin/assets/28616817/f2baec83-4a1b-4469-887b-df641b1e9aa8">

<img width="716" alt="image" src="https://github.com/getActivity/AndroidProject-Kotlin/assets/28616817/e3645a97-b374-43f5-8e7e-a4022af7ea45">

<img width="699" alt="image" src="https://github.com/getActivity/AndroidProject-Kotlin/assets/28616817/ced28f72-034e-4c64-ad6f-ae78270eda1a">

**Comment by getActivity** [comment]
小伙子，我验证了一下，并没有出现你说的包体能小 2M 的问题。

**Comment by syxc** [comment]
感谢阿轮细心的验证，容我我回头再测几次再来反馈，我的环境：

- agp 7.2.2
- gradle 7.3.3
- kotlin 1.7.21

**Comment by syxc** [comment]
配置 1：  

library.base
```
defaultConfig {
  // 模块混淆配置
  consumerProguardFiles 'proguard-base.pro'
}
```

app
```
...
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-sdk.pro', 'proguard-app.pro'
...
```

![WX20231219-222610@2x](https://github.com/getActivity/AndroidProject-Kotlin/assets/315633/a50e838d-4063-41cf-8bea-e3d5ed18d218)

配置 2：  

library.base
```
defaultConfig {
  // 模块混淆配置
  // consumerProguardFiles 'proguard-base.pro'
}
```

app
```
...
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-sdk.pro', 'proguard-app.pro'
...
```

![WX20231219-222803@2x](https://github.com/getActivity/AndroidProject-Kotlin/assets/315633/e3bfa063-6c11-47a7-ac57-f8c06793d3eb)

**Comment by getActivity** [comment]
<img width="756" alt="image" src="https://github.com/getActivity/AndroidProject-Kotlin/assets/28616817/46d0b8c5-fc67-4e9c-a631-0518ee3b95d9">

* 小伙子，针对你这个问题，我把`consumerProguardFiles 'proguard-base.pro'` 的混淆配置注释掉就能复现这个问题，但是这个问题和用不用 `proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-sdk.pro', 'proguard-app.pro'` 没什么关系，不信你可以测试一下。

**Comment by getActivity** [comment]
另外你确定把 `proguard-base.pro` 注释掉没有什么问题？里面是一些不能被混淆类的规则。

**Comment by syxc** [comment]
> 另外你确定把 `proguard-base.pro` 注释掉没有什么问题？里面是一些不能被混淆类的规则。

我理解你的意思，所以我提到了一个前提，在不影响正常功能的情况，有没有优化的可能，抛砖引玉～

**Comment by getActivity** [comment]
@syxc 小伙子，我这两天忙于工作，不是特别有空，我星期六日找时间研究一下，但是为了保险起见，建议你不要注释 `proguard-base.pro`，避免混淆出现 Bug，等我研究出来结果了会在这个 issue 下面同步你。

**Comment by syxc** [comment]
> @syxc 小伙子，我这两天忙于工作，不是特别有空，我星期六日找时间研究一下，但是为了保险起见，建议你不要注释 `proguard-base.pro`，避免混淆出现 Bug，等我研究出来结果了会在这个 issue 下面同步你。

明白，工作优先。

**Comment by getActivity** [comment]
<img width="1029" alt="image" src="https://github.com/getActivity/AndroidProject-Kotlin/assets/28616817/c4660e49-d263-48df-babf-5ead04d729a6">

**Comment by getActivity** [comment]
<img width="512" alt="image" src="https://github.com/getActivity/AndroidProject-Kotlin/assets/28616817/81172949-9144-4f3b-902a-28c78253751d">

**Comment by getActivity** [comment]
小伙子，我查出来问题的根源，是这个混淆规则写得有问题，目前我已经将这条混淆规则去除掉，你可以验证一下，另外建议你再去除掉这个规则之后，进行全方位的自测及测试的验证后再上线。

**Comment by syxc** [comment]
> 小伙子，我查出来问题的根源，是这个混淆规则写得有问题，目前我已经将这条混淆规则去除掉，你可以验证一下，另外建议你再去除掉这个规则之后，进行全方位的自测及测试的验证后再上线。

好的，多谢轮子哥🤝
