### ISSUE TITLE
无法改变手机底部导航栏的颜色

### ISSUE THREAD

**Issue by GuoLiangjun123** [getActivity/AndroidProject-Kotlin#45]
## 问题描述

* 框架版本【必填】：最新版

* 问题描述【必填】：activity中设置底部导航栏的颜色，底部导航栏的颜色没变！

* 复现步骤【必填】：activity中重写    override fun createStatusBarConfig(): ImmersionBar {
        return super.createStatusBarConfig() 
            .navigationBarColor(R.color.black)
    } 颜色并未改变

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：小米10

* 出现问题的安卓版本【必填】：安卓13

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分（小米10）

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，这个问题属于 ImmersionBar 框架的问题，我并不是此框架的作者，你需要反馈框架原作者处理。

**Comment by LeqiaoW** [comment]
感谢您的来信，邮件我已收到！
