### ISSUE TITLE
构建项目成功厚，打开xxxactivity，出现大面积爆红，如果不点进去则可以正常运行

### ISSUE THREAD

**Issue by AdminQQZ** [getActivity/AndroidProject-Kotlin#49]
## 问题描述

构建项目成功厚，打开xxxactivity，出现大面积爆红，如果不点进去则可以正常运行
![image](https://github.com/getActivity/AndroidProject-Kotlin/assets/12959954/8185803e-159e-428e-973a-9fe6bd20b9be)

我使用的是 jdk 1.8

## 其他

![image](https://github.com/getActivity/AndroidProject-Kotlin/assets/12959954/8a0c597b-b4d0-4fef-8b99-5e5df7cef9bc)

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写
