### ISSUE TITLE
底部弹出的dialog，底部导航栏颜色怎么保持不变

### ISSUE THREAD

**Issue by yan885283** [getActivity/AndroidProject-Kotlin#6]
大佬，请问底部弹出的dialog，底部导航栏颜色怎么保持不变，现在底部弹出dialog，导航栏就会变成灰色，看起来很怪，请大佬指教，不胜感激

**Comment by getActivity** [comment]
小伙子，你可以看一下 [ImmersionBar](https://github.com/gyf-dev/ImmersionBar) 这个框架是怎么实现的 Dialog 沉浸式的。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
