### ISSUE TITLE
mvvm以及jetpack这些有打算加入吗,轮子哥

### ISSUE THREAD

**Issue by lydlovezjr** [getActivity/AndroidProject-Kotlin#9]

**Comment by CPC-Coder** [comment]
同上

**Comment by getActivity** [comment]
文档上面不是写了？

**Comment by lydlovezjr** [comment]
AndroidProject 里面其实有运用到和 Jetpack 相关的技术，例如 Lifecycle 特性，在 BaseDialog 加入了此特性，不仅如此，里面引入的 EasyHttp 网络请求框架也采用了 Lifecycle 特性来管控网络请求，Lifecycle 是一个好东西，把组件的生命周期抽象化了，这样我们无需要关心这个组件是 Activity 或 Fragment，又或者是其他类型的组件。

但是除了 Lifecycle 组件之外，LiveData 和 ViewModel 组件在 AndroidProject 基本没有用到，这个是因为 AndroidProject 有自己的代码设计思想，只会集成一些合适的代码库，不会一味地去追求什么全家桶，框架选型是要综合考虑很多方面的因素，并没有大家想得那么简单。

**Comment by YangJian007** [comment]
我在轮子哥这个kt工程的基础上改造了一下子，增加了组件化、MVVM、jetpack、retrofit+协程+flow、Hilt的支持，目前已运用到实际项目，非常不错 https://github.com/YangJian007/AtmkArch
